Teste_BRASILAPI/Models/EnderecoModel.cs
using System.Text.Json.Serialization;

namespace Teste_BRASILAPI.Models
{
    public class EnderecoModel
    {
        [JsonPropertyName("cep")]
        public string? Cep { get; set; }

        [JsonPropertyName("state")]
        public string? Estado { get; set; }

        [JsonPropertyName("city")]
        public string? Cidade { get; set; }

        [JsonPropertyName("neighborhood")]
        public string? Região { get; set; }

        [JsonPropertyName("street")]
        public string? Rua { get; set; }

        [JsonPropertyName("service")]
        public string? Servico { get; set; }

        public bool Verificacao { get; set; }

        public string? ErrorMessage { get; set; }


    }
}

Teste_BRASILAPI/Models/ErrorViewModel.cs
namespace Teste_BRASILAPI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Teste_BRASILAPI/Models/PokemonModel.cs
using System.Text.Json.Serialization;

namespace Teste_BRASILAPI.Models;

public class PokemonModel
{
	[JsonPropertyName("name")]
	public string? Nome { get; set; }

	[JsonPropertyName("id")]
	public int Id { get; set; }

	[JsonPropertyName("height")]
	public long Altura { get; set; }

	[JsonPropertyName("weight")]
	public long Peso { get; set; }

	[JsonPropertyName("sprites")]
	public Sprites? Sprite { get; set; }

	[JsonPropertyName("types")]
	public List<TypeElement>? Tipos { get; set; }

	[JsonPropertyName("officialArtworkUrl")]
	public string? OfficialArtworkUrl { get; set; }
	public string? IconUrl { get; set; }
	public bool Verificacao { get; set; }
	public string? ErrorMessage { get; set; }
	public List<Evolution>? Evolutions { get; set; }
	public List<Variant>? Variants { get; set; }
	public string TipoPrincipal { get; internal set; }
}

//SPRITES DO PKM
public class Sprites
{
	[JsonPropertyName("other")]
	public OtherSprites? Other { get; set; }
}

public class OtherSprites
{
	[JsonPropertyName("official-artwork")]
	public OfficialArtwork? OfficialArtwork { get; set; }
}

public class OfficialArtwork
{
	[JsonPropertyName("front_default")]
	public string? FrontDefault { get; set; }
}

//TIPOS DO PKM
public class TypeElement
{
	[JsonPropertyName("slot")]
	public long Slot { get; set; }

	[JsonPropertyName("type")]
	public Type? Type { get; set; }
}

public class Type
{
	[JsonPropertyName("name")]
	public string? Name { get; set; }

	[JsonPropertyName("url")]
	public Uri? Url { get; set; }
}

public class Evolution
{
	public string? Name { get; set; }
	public string? ImageUrl { get; set; }
	public string? Id { get; set; }
}

public class Variant
{
	public string? Name { get; set; }
	public string? ImageUrl { get; set; }
	public string? Id { get; set; }
}

public class SpeciesModel
{
	[JsonPropertyName("evolution_chain")]
	public EvolutionChainUrl EvolutionChain { get; set; }

	[JsonPropertyName("varieties")]
	public List<Variety> Varieties { get; set; }
}

public class EvolutionChainUrl
{
	[JsonPropertyName("url")]
	public string Url { get; set; }
}

public class Variety
{
	[JsonPropertyName("pokemon")]
	public VarietyPokemon Pokemon { get; set; }
}

public class VarietyPokemon
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
}

public class EvolutionChain
{
	[JsonPropertyName("chain")]
	public EvolutionNode Chain { get; set; }
}

public class EvolutionNode
{
	[JsonPropertyName("species")]
	public Species Species { get; set; }

	[JsonPropertyName("evolves_to")]
	public List<EvolutionNode> EvolvesTo { get; set; }
}

public class Species
{
	[JsonPropertyName("name")]
	public string Name { get; set; }
}

public class EvolutionChainModel
{
	[JsonPropertyName("chain")]
	public ChainLink Chain { get; set; }
}

public class ChainLink
{
	[JsonPropertyName("species")]
	public EvolutionSpecies Species { get; set; }

	[JsonPropertyName("evolves_to")]
	public List<ChainLink> EvolvesTo { get; set; }
}

public class EvolutionSpecies
{
	[JsonPropertyName("name")]
	public string Name { get; set; }

	[JsonPropertyName("url")]
	public string Url { get; set; }
}
public class PokemonListResponse
{
	[JsonPropertyName("results")]
	public List<PokemonListItem> Results { get; set; }
}

public class PokemonListItem
{
	[JsonPropertyName("name")]
	public string Name { get; set; }

	[JsonPropertyName("url")]
	public string Url { get; set; }
    public int Id { get; set; }
    public string ImageUrl { get; set; }
}

Teste_BRASILAPI/Controllers/EnderecoController.cs
using Microsoft.AspNetCore.Mvc;
using Teste_BRASILAPI.Interfaces;
using Teste_BRASILAPI.Services;

namespace Teste_BRASILAPI.Controllers
{
    [ApiController]
    [Route("{controller}")]
    public class EnderecoController : Controller
    {
        private readonly EnderecoService _enderecoService;

        public EnderecoController(EnderecoService enderecoService)
        {
            _enderecoService = enderecoService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet("{action}")] 
        public async Task<IActionResult> EnderecoInfo(string cep)
        {
            var response = await _enderecoService.BuscarEndereco(cep);

           return View(response);
        }

  
    }
}

Teste_BRASILAPI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Teste_BRASILAPI.Models;

namespace Teste_BRASILAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Teste_BRASILAPI/Controllers/PokemonController.cs
using Microsoft.AspNetCore.Mvc;
using Teste_BRASILAPI.Models;
using Teste_BRASILAPI.Services;
using System.Threading.Tasks;
using System.Text.Json;

namespace Teste_BRASILAPI.Controllers;

[ApiController]
[Route("{controller}")]
public class PokemonController : Controller
{
	private readonly PokemonService _pokemonService;

	private readonly Dictionary<int, string> _tipoParaImagem = new Dictionary<int, string>
		{
			{ 1, "normal.png" },
			{ 2, "fighting.png" },
			{ 3, "flying.png" },
			{ 4, "poison.png" },
			{ 5, "ground.png" },
			{ 6, "rock.png" },
			{ 7, "bug.png" },
			{ 8, "ghost.png" },
			{ 9, "steel.png" },
			{ 10, "fire.png" },
			{ 11, "water.png" },
			{ 12, "grass.png" },
			{ 13, "electric.png" },
			{ 14, "psychic.png" },
			{ 15, "ice.png" },
			{ 16, "dragon.png" },
			{ 17, "dark.png" },
			{ 18, "fairy.png" }
		};

	public PokemonController(PokemonService pokemonService)
	{
		_pokemonService = pokemonService;
	}

	public IActionResult Index()
	{
		return View();
	}

	[HttpGet("action")]
	public async Task<IActionResult> PokemonInfo(string name)
	{
		PokemonModel pokemon;

		try
		{
			pokemon = await _pokemonService.BuscarPokemon(name);

			if (pokemon == null)
			{
				pokemon = new PokemonModel
				{
					Verificacao = false,
					ErrorMessage = "Pokémon não encontrado.",
					OfficialArtworkUrl = Url.Content("~/images/pokemon-not-found.png")
				};
			}
			else
			{
				pokemon.Verificacao = true;
				pokemon.TipoPrincipal = GetTipoPrincipal(pokemon);
			}
		}
		catch
		{
			pokemon = new PokemonModel
			{
				Verificacao = false,
				ErrorMessage = "Pokémon não encontrado.",
				OfficialArtworkUrl = Url.Content("~/images/pokemon-not-found.png")
			};
		}

		return View("PokemonInfo", pokemon);
	}
	// Função para obter o tipo principal do Pokémon
	private string GetTipoPrincipal(PokemonModel pokemon)
	{
		if (pokemon.Tipos != null && pokemon.Tipos.Count > 0)
		{
			return pokemon.Tipos[0].Type.Name.ToLower(); // Retorna o nome do tipo principal em minúsculas
		}
		return "default"; // Caso não haja tipos, retorna uma classe padrão
	}

    [HttpGet("all")]
    public async Task<IActionResult> AllPokemon()
    {
        var allPokemon = await _pokemonService.GetAllPokemon();
        return View("AllPokemon", allPokemon);
    }
}

Teste_BRASILAPI/Views/Endereco/EnderecoInfo.cshtml
@model EnderecoModel

@if (Model.Verificacao)
{
    <div style="height: 100vh; " class=" d-flex flex-column justify-content-start align-items-center pt-5 my-5 text-light  ">
        <h1 class="text-center mb-5"> Segue mais informaçoes sobre o CEP buscado:</h1>

        <form asp-controller="Endereco" asp-action="EnderecoInfo"> 
            <div style="background-image:linear-gradient(#a6a6a6, #ffff);" class="d-flex flex-column align-items-center
            justify-content-start  pt-5 pb-4 px-5 rounded">
                <h3 style="color: #051130; font-weight:700;" class="mb-5"> CEP REQUERIDO: <span style="color:white;"> @Model.Cep </span> </h3>
                <p> Estado: <span style="color:#EF6B48; font-weight:600">@Model.Estado</span> </p>
                <p> Cidade: <span style="color:#EF6B48; font-weight:600">@Model.Cidade</span></p>
                <p> Bairro: <span style="color:#EF6B48; font-weight:600">@Model.Região</span></p>
                <p> Rua: <span style="color:#EF6B48; font-weight:600">@Model.Rua</span></p>

                <button asp-controller="Home" asp-action="Index" class="rounded px-4 py-1 text-light mt-4 border-0" style="font-size: 24px;" type="submit"> Voltar </button>
            </div>
        </form>
        
    </div>

}
else
{
    <h2> @Model.ErrorMessage</h2>
    
}

Teste_BRASILAPI/Views/Endereco/Index.cshtml
@model EnderecoModel

<div style="height:100vh" ; class="d-flex flex-column align-items-center justify-content-center">

    <div style="background-image:linear-gradient(#a6a6a6, #ffff);" class="d-flex flex-column align-items-center
    justify-content-start p-5 rounded">

        <h1 style="color: #051130; font-weight:600; " class="display-4 mb-3">Buscador de CEP</h1>

        <form method="get" asp-controller="Endereco" asp-action="EnderecoInfo" role="form">

            <input asp-for="Cep" style="width:340px; padding:7.2px 9px; margin-right:4px; font-size:18px" class="my-4 rounded" name="cep" placeholder="Digite seu CEP" />

            <button class="p-2 rounded text-light border-0" style="font-size:19px; font-weight:bolder" type="submit" value="Cep"> Buscar  </button>
        </form>

    </div>



</div>

Teste_BRASILAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<div style="height:100vh"; class="d-flex flex-column align-items-center justify-content-center text-light">

  <h1> Escolha a sua API e divirta-se </h1>

  

</div>

Teste_BRASILAPI/Views/Pokemon/AllPokemon.cshtml
@model List<Teste_BRASILAPI.Models.PokemonListItem>

@{
    ViewData["Title"] = "All Pokémon";
}

<h1>All Pokémon</h1>

<table class="table">
    <thead>
        <tr>
            <th>Image</th>
            <th>Number</th>
            <th>Name</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pokemon in Model)
        {
            <tr>
                <td>
                    <img src="@pokemon.ImageUrl" alt="@pokemon.Name" width="100" height="100" />
                </td>
                <td>#@pokemon.Id</td>
                <td>@pokemon.Name</td>
                <td>
                    <a href="@Url.Action("PokemonInfo", "Pokemon", new { name = pokemon.Name })">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Teste_BRASILAPI/Views/Pokemon/Index.cshtml
@model PokemonModel

<div style="height:100vh" ; class="d-flex flex-column align-items-center justify-content-center">
    <div style="background-image:linear-gradient(#a6a6a6, #ffff);" class="d-flex flex-column align-items-center
    justify-content-start p-5 rounded">
        <h1 style="color: #051130; font-weight:600; " class="display-4 mb-3">Buscar Pokémon</h1>

        <form method="get" asp-controller="Pokemon" asp-action="PokemonInfo" role="form">
            <input asp-for="Nome" style="width:340px; padding:7.2px 9px; margin-right:4px; font-size:18px" class="my-4 rounded" name="name" placeholder="Digite o Id ou Nome do Pokémon" />
            <button class="p-2 rounded text-light border-0" style="font-size:19px; font-weight:bolder" type="submit" value="Nome">Buscar</button>
        </form>
    </div>
</div>

Teste_BRASILAPI/Views/Pokemon/PokemonInfo.cshtml
@model Teste_BRASILAPI.Models.PokemonModel

<link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">

@if (Model.Verificacao)
{
	<div class="d-flex flex-column align-items-center justify-content-center">
		<form method="get" asp-controller="Pokemon" asp-action="PokemonInfo" role="form">
			<input id="nameInput" asp-for="Nome" style="width:340px; padding:7.2px 9px; margin-right:4px; font-size:18px" class="my-4 rounded" name="name" placeholder="Digite o Id ou Nome do Pokémon" />
			<button class="p-2 rounded text-light border-0" style="font-size:19px; font-weight:bolder" type="submit" value="Nome">Buscar</button>
		</form>

		<form id="pokemonForm" method="get" asp-controller="Pokemon" asp-action="PokemonInfo">
			<div class="container card-pokemon bg-img">
				<img class="pkm-icon" src="@Model.IconUrl" />
				<h3>#@Model.Id</h3>
				<h3>• @Model.Nome.ToUpper() •</h3>
				<img class="pkm-img" src="@Model.Sprite.Other.OfficialArtwork.FrontDefault" />
				<div class="pkm-infos">
					<div class="label-hw d-flex flex-column align-items-center justify-content-center">
						<p class="d-flex align-items-center m-0 hw-text">
							<i class="uil uil-ruler"></i> Altura
						</p>
						<span class="hw">@Model.Altura M</span>
					</div>
					<div class="pkm-types">
						@foreach (var tipo in Model.Tipos)
						{
							<img src="~/images/types/@(tipo.Type.Name).png" alt="@tipo.Type.Name" title="@tipo.Type.Name" />
						}
					</div>
					<div class="label-hw d-flex flex-column align-items-center justify-content-center">
						<p class="d-flex align-items-center m-0 hw-text">
							<i class="uil uil-dumbbell"></i> Peso
						</p>
						<span class="hw">@Model.Peso KG</span>
					</div>
				</div>

				<br />

				@if (Model.Evolutions != null && Model.Evolutions.Any())
				{
					<h4>Evoluções:</h4>
					<div class="evolutions">
						@foreach (var evolution in Model.Evolutions)
						{
							<div class="evolution" onclick="selecionarPokemon('@evolution.Name')">
								<img src="@evolution.ImageUrl" />
								<span>@evolution.Name.ToUpper()</span>
							</div>
						}
					</div>
				}
				@if (Model.Variants != null && Model.Variants.Any())
				{
					<h4>Variantes:</h4>
					<div class="variants">
						@foreach (var variant in Model.Variants)
						{
							<div class="variant" onclick="selecionarPokemon('@variant.Name')">
								<img src="@variant.ImageUrl" />
								<span>@variant.Name.ToUpper()</span>
							</div>
						}
					</div>
				}
			</div>
			<input type="text" name="name" style="display: none;" />
		</form>
	</div>
}
else
{
	<form asp-controller="Pokemon" asp-action="PokeInfo">
		<div class="container card-pokemon bg-img">
			<h2>@Model.ErrorMessage</h2>
			<img src="@Model.OfficialArtworkUrl" alt="Pokémon não encontrado" style="max-width: 300px;" />
			<button asp-controller="Pokemon" asp-action="Index" class="rounded px-4 py-1 text-light mt-4 border-0" style="font-size: 24px;" type="submit"> Voltar </button>
		</div>
	</form>
}

<script>
	//#region Função que adiciona a cor do tipo no fundo
	// Função para definir a cor do gradiente radial com base no tipo do Pokémon
	function setGradientColor(tipoPrincipal, selector) {
		const bodyPkm = document.querySelector('body');
		const cardPokemon = document.querySelector('.card-pokemon');
		const iconPokemon = document.querySelector('.pkm-icon');
		let gradientColor;
		switch (tipoPrincipal) {
			case 'normal':
				gradientColor = 'rgb(168, 168, 120)';
				break;
			case 'fighting':
				gradientColor = 'rgb(192, 48, 40)';
				break;
			case 'flying':
				gradientColor = 'rgb(168, 144, 240)';
				break;
			case 'poison':
				gradientColor = 'rgb(160, 64, 160)';
				break;
			case 'ground':
				gradientColor = 'rgb(224, 192, 104)';
				break;
			case 'rock':
				gradientColor = 'rgb(184, 160, 56)';
				break;
			case 'bug':
				gradientColor = 'rgb(168, 184, 32)';
				break;
			case 'ghost':
				gradientColor = 'rgb(112, 88, 152)';
				break;
			case 'steel':
				gradientColor = 'rgb(184, 184, 208)';
				break;
			case 'fire':
				gradientColor = 'rgb(240, 128, 48)';
				break;
			case 'water':
				gradientColor = 'rgb(104, 144, 240)';
				break;
			case 'grass':
				gradientColor = 'rgb(120, 200, 80)';
				break;
			case 'electric':
				gradientColor = 'rgb(248, 208, 48)';
				break;
			case 'psychic':
				gradientColor = 'rgb(248, 88, 136)';
				break;
			case 'ice':
				gradientColor = 'rgb(152, 216, 216)';
				break;
			case 'dragon':
				gradientColor = 'rgb(112, 56, 248)';
				break;
			case 'dark':
				gradientColor = 'rgb(112, 88, 72)';
				break;
			case 'fairy':
				gradientColor = 'rgb(238, 153, 172)';
				break;
			default:
				gradientColor = 'rgb(0, 0, 0)'; // Cor padrão
				break;
		}
		// Aplica a cor no gradiente radial
		cardPokemon.style.backgroundImage = `url(/images/half-pokeball.svg), radial-gradient(80% 80% at 50% bottom, ${gradientColor}, rgba(6, 14, 32, 0.8))`;
		iconPokemon.style.backgroundImage = `url(), radial-gradient(80% 80% at 50% bottom, ${gradientColor}, rgba(6, 14, 32, 0.8))`;
		bodyPkm.style.backgroundImage = `url(), radial-gradient(80% 80% at 50% top, ${gradientColor}, rgba(6, 14, 32, 0.8))`;
	}
	// Chamada inicial para definir a cor com base no tipo principal do Pokémon
	setGradientColor('@Model.TipoPrincipal', '.card-pokemon');
	setGradientColor('@Model.TipoPrincipal', '.pkm-icon');
	//#endregion
	//#region Função para retornar evolução selecionada
	function selecionarPokemon(nomePokemon) {
		// Obtém o formulário pelo ID
		const form = document.getElementById('pokemonForm');

		// Verifica se o formulário foi encontrado
		if (form) {
			// Obtém o input dentro do formulário pelo nome
			const inputNome = form.querySelector('input[name="name"]');

			// Verifica se o input foi encontrado
			if (inputNome) {
				// Define o valor do input com o nome do Pokémon selecionado
				inputNome.value = nomePokemon;

				// Submete o formulário para o controller
				form.submit();
			} else {
				console.error('Elemento input[name="name"] não encontrado.');
			}
		} else {
			console.error('Formulário com ID "pokemonForm" não encontrado.');
		}
	}
	//#endregion
</script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel/slick/slick.min.js"></script>

<style>
	i {
		color: #fff;
		font-size: 24px;
	}

	.pkm-img {
		filter: drop-shadow(10px 7px 10px #000);
		width: 300px;
		transition: 0.5s;
	}

		.pkm-img:hover {
			transform: scale(1.10);
		}

	.pkm-icon {
		width: 100px;
		margin-top: 10px;
		margin-left: 80%;
		padding: 10px;
		border-radius: 100%;
		border: 3px solid #fff;
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.hw {
		color: #fff;
		font-weight: 700;
		font-size: 25px;
		display: flex;
		justify-content: center;
		align-items: center;
		gap: 5px;
	}

	.hw-text {
		font-size: 1rem;
		color: #fff;
		font-weight: 500;
		gap: 5px;
	}

	.pkm-types {
		display: flex;
		flex-direction: column;
		gap: 10px;
	}

	.pkm-infos {
		display: flex;
		justify-content: center;
		align-items: center;
		flex-direction: row;
		gap: 20px;
		color: #fff;
	}

	.card-pokemon {
		display: flex;
		align-items: center;
		justify-content: center;
		flex-direction: column;
		border-radius: 24px;
		border: 1px solid hsla(0,0%,100%,.2);
		background-size: 50%, auto;
		background-repeat: no-repeat;
		width: 500px;
		color: #fff;
	}

	.evolutions, .variants {
		display: flex;
		gap: 10px;
	}

	.evolution, .variant {
		display: flex;
		flex-direction: column;
		align-items: center;
	}

		.evolution img, .variant img {
			width: 150px;
			transition: 0.5s;
		}

			.evolution img:hover, .variant img:hover {
				transform: scale(1.10);
			}

		.evolution span, .variant span {
			color: #fff;
		}
</style>

Teste_BRASILAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Teste_BRASILAPI</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Teste_BRASILAPI.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Endereco" asp-action="Index">Buscador de CEP</a>
						</li>

						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Pokemon" asp-action="Index">Buscar Pokémon</a>
						</li>

						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Pokemon" asp-action="AllPokemon">Todos os Pokémon</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer style="background-color:white" class="border-top footer text-muted text-center">
		<div class="container">
			&copy; 2024 - Jackson Silva - Estudos API
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>